name: Update README with Hashnode Articles

on:
  schedule:
    # Run daily at midnight (adjust as needed)
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"  # Specify the version you're using

      # Install dependencies (if any)
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Install requests if you don't have a requirements.txt

      # Run the Python script
      - name: Run Update Script
        run: |
          python automate_profile_hashnode_article_population.py

      # Check if README.md is modified and commit changes
      - name: Check if README.md is modified
        run: |
          git diff README.md
          if git diff --quiet README.md; then
            echo "No changes to commit"
            exit 0
          else
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add README.md
            git commit -m "Update README with latest Hashnode articles"
            git push
          fi
