name: Update README with Hashnode Articles

on:
  schedule:
    # Run daily at midnight (adjust as needed)
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x" # Replace with the Python version you're using

      # Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      # Install dependencies using Poetry
      - name: Install Dependencies
        run: |
          poetry install

      # Run the Python script
      - name: Run Update Script
        run: python automate_profile_hashnode_article_population.py

      # Commit and push changes
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update README with latest Hashnode articles"
          git push
